# ref: # https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/patterns/gitops/getting-started-argocd/k8s/game-2048.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: games-applications
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: workloads
      finalizers:
        # This finalizer is for demo purposes, in production remove apps using argocd CLI "argocd app delete workload --cascade"
        # When you invoke argocd app delete with --cascade, the finalizer is added automatically.
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: 'https://github.com/reiichii/EKS-de-asobo'
        path: 'argocd_apps/game_manifests'
        targetRevision: 'main'
      destination:
        name: '{{name}}'
      syncPolicy:
        automated:
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 60
