apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ops-applications
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: ops-applications
    spec:
      project: default
      source:
        repoURL: 'https://github.com/reiichii/EKS-de-asobo'
        path: 'argocd_apps/ops_manifests'
        targetRevision: 'main'
        directory:
          recurse: false
      destination:
        namespace: default
        name: '{{name}}'
      syncPolicy:
        automated:
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 60
